namespace UnbloatDB;

static internal class Variants
{
    public static string[] Location =
    {
        "Barrow-in-Furness",
        "Bedford",
        "Birkenhead",
        "Bishop Auckland",
        "Blackpool",
        "Bloxwich",
        "Blyth",
        "Bolton",
        "Boston",
        "Bournemouth",
        "Bridgwater",
        "Brighouse",
        "Burton upon Trent",
        "Camborne",
        "Carlisle",
        "Castleford",
        "Cheadle",
        "Clay Cross",
        "Cleator Moor",
        "Colchester",
        "Corby",
        "Crawley",
        "Crewe",
        "Darlington",
        "Darwen",
        "Dewsbury",
        "Doncaster",
        "Dudley",
        "Glastonbury",
        "Goldthorpe",
        "Goole",
        "Grays",
        "Great Yarmouth",
        "Grimsby",
        "Harlow",
        "Hartlepool",
        "Hastings",
        "Hereford",
        "Ipswich",
        "Keighley and Shipley",
        "Kidsgrove",
        "King’s Lynn",
        "Kirkby-in-Ashfield",
        "Leyland",
        "Lincoln",
        "Long Eaton",
        "Loughborough",
        "Lowestoft",
        "Mablethorpe",
        "Mansfield",
        "Margate",
        "Middlebrough",
        "Millom",
        "Milton Keynes",
        "Morley",
        "Nelson",
        "Newark-on-Trent",
        "Newcastle-under-Lyme",
        "Newhaven",
        "Northampton",
        "Norwich",
        "Nuneaton",
        "Oldham",
        "Penzance",
        "Peterborough",
        "Preston",
        "Redcar",
        "Redditch",
        "Rochdale",
        "Rotherham",
        "Rowley Regis",
        "Runcorn",
        "Scarborough",
        "Scunthorpe",
        "Skegness",
        "Smethwick",
        "Southport",
        "St Helens",
        "St Ives",
        "Stainforth",
        "Stapleford",
        "Stavele",
        "Stevenage",
        "Stocksbridge"
    };
}